---
apiVersion: v1
kind: Service
metadata:
  name: metastore-new-svc
spec:
  ports:
  - port: 9083
  selector:
    app: metastore-new
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metastore-new
spec:
  selector:
    matchLabels:
      app: metastore-new
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metastore-new
    spec:
      containers:
      - name: metastore
        image: clen/flink:hive_metastore_1.0.0
        imagePullPolicy: Always
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: my-s3-keys
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: my-s3-keys
              key: secret-key
        ports:
        - containerPort: 9083
        args: ["-p", "9083"]
        resources:
          requests:
            memory: "8G"
            cpu: 2
      imagePullSecrets:
      - name: regcred
